version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/process-pension-service-narendra:2"
        LoadBalancerInfo:
          ContainerName: "pensioner-detail-service"
          ContainerPort: "8082"
        PlatformVersion: "LATEST"